import { HistoricalEvent, TimelineScale } from './types';

export const SCALES: TimelineScale[] = [
  { level: 0, yearsPer1000Px: 500000, name: 'Prehistoric', minYear: -10000000, maxYear: 10000000 },
  { level: 1, yearsPer1000Px: 100000, name: 'Early Humans', minYear: -500000, maxYear: 500000 },
  { level: 2, yearsPer1000Px: 20000, name: 'Civilization Dawn', minYear: -100000, maxYear: 100000 },
  { level: 3, yearsPer1000Px: 5000, name: 'Ancient Empires', minYear: -20000, maxYear: 20000 },
  { level: 4, yearsPer1000Px: 1000, name: 'Classical Era', minYear: -5000, maxYear: 5000 },
  { level: 5, yearsPer1000Px: 200, name: 'Medieval Era', minYear: -1000, maxYear: 3000 },
  { level: 6, yearsPer1000Px: 50, name: 'Modern Era', minYear: 1500, maxYear: 2100 },
  { level: 7, yearsPer1000Px: 10, name: 'Contemporary', minYear: 1900, maxYear: 2050 },
];

export const EVENTS: HistoricalEvent[] = [
  // Prehistoric
  { id: 'h_sapiens', year: -200000, track: 'World', title: 'Emergence of Homo sapiens', title_zh: '智人出现', tags: ['evolution', 'humanity'] },
  { id: 'out_of_africa', year: -70000, track: 'World', title: 'Out of Africa Migration', title_zh: '走出非洲', tags: ['migration', 'humanity'] },
  { id: 'cave_art', year: -40000, track: 'World', title: 'First Cave Paintings', title_zh: '最早的洞穴壁画', tags: ['art', 'culture'] },
  { id: 'agriculture_world', year: -10000, track: 'World', title: 'Agricultural Revolution', title_zh: '农业革命', tags: ['neolithic', 'society'] },
  { id: 'peiligang_culture', year: -7000, track: 'China', title: 'Peiligang Culture', title_zh: '裴李岗文化', tags: ['neolithic', 'culture'] },
  { id: 'sumer', year: -4500, track: 'World', title: 'Sumerian Civilization', title_zh: '苏美尔文明', tags: ['civilization', 'writing'] },
  { id: 'egypt_unified', year: -3100, track: 'World', title: 'Unification of Egypt', title_zh: '埃及统一', tags: ['civilization', 'egypt'] },
  
  // Ancient
  { id: 'xia', year: -2070, track: 'China', title: 'Xia Dynasty (Legendary)', title_zh: '夏朝（传说）', tags: ['dynasty', 'legend'] },
  { id: 'pyramids', year: -2550, track: 'World', title: 'Great Pyramid of Giza', title_zh: '吉萨大金字塔', tags: ['monument', 'egypt'] },
  { id: 'shang', year: -1600, track: 'China', title: 'Shang Dynasty / Oracle Bones', title_zh: '商朝/甲骨文', tags: ['dynasty', 'bronze age'] },
  { id: 'hittite_empire', year: -1600, track: 'World', title: 'Hittite Empire', title_zh: '赫梯帝国', tags: ['empire', 'iron age'] },
  { id: 'zhou', year: -1046, track: 'China', title: 'Zhou Dynasty, Mandate of Heaven', title_zh: '周朝，天命', tags: ['dynasty', 'philosophy'] },
  { id: 'olympics', year: -776, track: 'World', title: 'First Olympic Games', title_zh: '第一次奥林匹克运动会', tags: ['greece', 'sport'] },
  { id: 'rome_found', year: -753, track: 'World', title: 'Founding of Rome', title_zh: '罗马建城', tags: ['city', 'republic'] },
  { id: 'confucius', year: -551, track: 'China', title: 'Birth of Confucius', title_zh: '孔子出生', tags: ['philosophy', 'confucianism'] },
  { id: 'buddha', year: -563, track: 'World', title: 'Birth of Buddha', title_zh: '佛陀出生', tags: ['religion', 'buddhism'] },
  { id: 'persian_wars', year: -499, track: 'World', title: 'Greco-Persian Wars', title_zh: '希波战争', tags: ['war', 'greece', 'persia'] },
  { id: 'warring_states', year: -475, track: 'China', title: 'Warring States Period', title_zh: '战国时期', tags: ['war', 'philosophy'] },
  { id: 'alexander', year: -336, track: 'World', title: 'Alexander the Great\'s Reign', title_zh: '亚历山大大帝统治', tags: ['conquest', 'hellenistic'] },
  { id: 'qin', year: -221, track: 'China', title: 'Qin Shi Huang Unifies China', title_zh: '秦始皇统一中国', tags: ['unification', 'empire'] },
  { id: 'han', year: -206, track: 'China', title: 'Han Dynasty / Silk Road', title_zh: '汉朝/丝绸之路', tags: ['dynasty', 'golden age'] },
  { id: 'rome_empire', year: -27, track: 'World', title: 'Roman Empire Begins', title_zh: '罗马帝国开始', tags: ['empire', 'augustus'] },
  
  // Classical / Post-Classical
  { id: 'paper', year: 105, track: 'China', title: 'Invention of Paper by Cai Lun', title_zh: '蔡伦发明造纸术', tags: ['invention', 'technology'] },
  { id: 'three_kingdoms', year: 220, track: 'China', title: 'Three Kingdoms Period', title_zh: '三国时期', tags: ['war', 'disunity'] },
  { id: 'constantine', year: 313, track: 'World', title: 'Edict of Milan', title_zh: '米兰敕令', tags: ['religion', 'christianity'] },
  { id: 'fall_of_rome', year: 476, track: 'World', title: 'Fall of the Western Roman Empire', title_zh: '西罗马帝国灭亡', tags: ['end of era', 'europe'] },
  { id: 'sui', year: 581, track: 'China', title: 'Sui Dynasty Reunifies China', title_zh: '隋朝统一中国', tags: ['dynasty', 'unification'] },
  { id: 'islam', year: 610, track: 'World', title: 'Prophet Muhammad\'s First Revelation', title_zh: '先知穆罕默德首次接受启示', tags: ['religion', 'islam'] },
  { id: 'tang', year: 618, track: 'China', title: 'Tang Dynasty', title_zh: '唐朝', tags: ['dynasty', 'culture', 'golden age'] },
  { id: 'an_lushan', year: 755, track: 'China', title: 'An Lushan Rebellion', title_zh: '安史之乱', tags: ['rebellion', 'war'] },
  { id: 'vikings', year: 793, track: 'World', title: 'Viking Age Begins', title_zh: '维京时代开始', tags: ['exploration', 'warfare'] },
  { id: 'movable_type', year: 1040, track: 'China', title: 'Invention of Movable Type', title_zh: '活字印刷术发明', tags: ['invention', 'printing'] },
  { id: 'song', year: 960, track: 'China', title: 'Song Dynasty', title_zh: '宋朝', tags: ['dynasty', 'invention'] },
  { id: 'norman_conquest', year: 1066, track: 'World', title: 'Norman Conquest of England', title_zh: '诺曼征服英格兰', tags: ['england', 'war'] },
  { id: 'crusades', year: 1096, track: 'World', title: 'The First Crusade', title_zh: '第一次十字军东征', tags: ['war', 'religion'] },
  { id: 'genghis_khan', year: 1206, track: 'World', title: 'Genghis Khan Unites Mongols', title_zh: '成吉思汗统一蒙古', tags: ['empire', 'conquest'] },
  { id: 'magna_carta', year: 1215, track: 'World', title: 'Magna Carta', title_zh: '大宪章', tags: ['law', 'rights'] },
  { id: 'yuan', year: 1271, track: 'China', title: 'Yuan Dynasty (Mongol Rule)', title_zh: '元朝（蒙古统治）', tags: ['dynasty', 'mongol'] },
  { id: 'marco_polo', year: 1275, track: 'World', title: 'Marco Polo in China', title_zh: '马可·波罗在中国', tags: ['exploration', 'culture'] },
  { id: 'black_death', year: 1347, track: 'World', title: 'The Black Death in Europe', title_zh: '黑死病在欧洲', tags: ['plague', 'disaster'] },
  
  // Early Modern
  { id: 'ming', year: 1368, track: 'China', title: 'Ming Dynasty / Forbidden City', title_zh: '明朝/紫禁城', tags: ['dynasty', 'exploration'] },
  { id: 'renaissance', year: 1400, track: 'World', title: 'The High Renaissance', title_zh: '文艺复兴盛期', tags: ['art', 'science'] },
  { id: 'printing_press', year: 1440, track: 'World', title: 'Gutenberg\'s Printing Press', title_zh: '古腾堡印刷机', tags: ['invention', 'information'] },
  { id: 'zheng_he', year: 1405, track: 'China', title: 'Zheng He\'s Voyages', title_zh: '郑和下西洋', tags: ['exploration', 'navy'] },
  { id: 'fall_constantinople', year: 1453, track: 'World', title: 'Fall of Constantinople', title_zh: '君士坦丁堡陷落', tags: ['ottoman', 'end of era'] },
  { id: 'columbus', year: 1492, track: 'World', title: 'Columbus Reaches Americas', title_zh: '哥伦布到达美洲', tags: ['exploration', 'colonialism'] },
  { id: 'reformation', year: 1517, track: 'World', title: 'Protestant Reformation', title_zh: '新教改革', tags: ['religion', 'protestantism'] },
  { id: 'copernicus', year: 1543, track: 'World', title: 'Copernican Revolution', title_zh: '哥白尼革命', tags: ['science', 'astronomy'] },

  // Modern
  { id: 'qing', year: 1644, track: 'China', title: 'Qing Dynasty', title_zh: '清朝', tags: ['dynasty', 'empire'] },
  { id: 'newton', year: 1687, track: 'World', title: 'Newton\'s Principia Mathematica', title_zh: '牛顿《自然哲学的数学原理》', tags: ['science', 'physics'] },
  { id: 'enlightenment', year: 1715, track: 'World', title: 'Age of Enlightenment', title_zh: '启蒙时代', tags: ['philosophy', 'reason'] },
  { id: 'industrial_rev', year: 1760, track: 'World', 'title': 'Industrial Revolution Begins', 'title_zh': '工业革命开始', tags: ['technology', 'society'] },
  { id: 'american_rev', year: 1776, track: 'World', title: 'American Revolution', title_zh: '美国革命', tags: ['revolution', 'usa'] },
  { id: 'french_rev', year: 1789, track: 'World', title: 'French Revolution', title_zh: '法国大革命', tags: ['revolution', 'france'] },
  { id: 'opium_war', year: 1839, track: 'China', title: 'First Opium War', title_zh: '第一次鸦片战争', tags: ['war', 'colonialism'] },
  { id: 'taiping_rebellion', year: 1850, track: 'China', title: 'Taiping Rebellion', title_zh: '太平天国运动', tags: ['rebellion', 'war'] },
  { id: 'us_civil_war', year: 1861, track: 'World', title: 'American Civil War', title_zh: '美国内战', tags: ['war', 'usa'] },
  { id: 'meiji_restoration', year: 1868, track: 'World', title: 'Meiji Restoration in Japan', title_zh: '日本明治维新', tags: ['modernization', 'japan'] },
  { id: 'boxer_rebellion', year: 1899, track: 'China', title: 'Boxer Rebellion', title_zh: '义和团运动', tags: ['rebellion', 'anti-foreign'] },
  { id: 'wright_brothers', year: 1903, track: 'World', title: 'First Powered Flight', title_zh: '首次动力飞行', tags: ['invention', 'aviation'] },
  { id: 'xinhai_rev', year: 1911, track: 'China', title: 'Xinhai Revolution', title_zh: '辛亥革命', tags: ['revolution', 'republic'] },
  { id: 'ww1', year: 1914, track: 'World', title: 'World War I', title_zh: '第一次世界大战', tags: ['war', 'global conflict'] },
  { id: 'russian_rev', year: 1917, track: 'World', title: 'Russian Revolution', title_zh: '俄国革命', tags: ['revolution', 'communism'] },
  { id: 'great_depression', year: 1929, track: 'World', title: 'The Great Depression', title_zh: '大萧条', tags: ['economy', 'crisis'] },
  { id: 'long_march', year: 1934, track: 'China', title: 'The Long March', title_zh: '长征', tags: ['communism', 'military'] },
  { id: 'ww2', year: 1939, track: 'World', title: 'World War II', title_zh: '第二次世界大战', tags: ['war', 'global conflict'] },
  { id: 'prc', year: 1949, track: 'China', title: 'Founding of the PRC', title_zh: '中华人民共和国成立', tags: ['politics', 'modern china'] },

  // Contemporary
  { id: 'korean_war', year: 1950, track: 'World', title: 'Korean War', title_zh: '朝鲜战争', tags: ['war', 'cold war'] },
  { id: 'dna_structure', year: 1953, track: 'World', title: 'Discovery of DNA Structure', title_zh: '发现DNA结构', tags: ['science', 'biology'] },
  { id: 'cultural_rev', year: 1966, track: 'China', title: 'Cultural Revolution', title_zh: '文化大革命', tags: ['politics', 'social movement'] },
  { id: 'moon_landing', year: 1969, track: 'World', title: 'Apollo 11 Moon Landing', title_zh: '阿波罗11号登月', tags: ['space', 'technology'] },
  { id: 'reform_opening', year: 1978, track: 'China', title: 'China\'s Reform and Opening-Up', title_zh: '中国改革开放', tags: ['economy', 'modernization'] },
  { id: 'fall_berlin_wall', year: 1989, track: 'World', title: 'Fall of the Berlin Wall', title_zh: '柏林墙倒塌', tags: ['cold war', 'end'] },
  { id: 'www', year: 1991, track: 'World', title: 'World Wide Web Goes Public', title_zh: '万维网公开发布', tags: ['technology', 'internet'] },
  { id: 'handover_hk', year: 1997, track: 'China', title: 'Hong Kong Handover', title_zh: '香港回归', tags: ['politics', 'decolonization'] },
  { id: '911', year: 2001, track: 'World', title: 'September 11 Attacks', title_zh: '911袭击', tags: ['terrorism', 'usa'] },
  { id: 'wto_china', year: 2001, track: 'China', title: 'China joins the WTO', title_zh: '中国加入WTO', tags: ['economy', 'globalization'] },
  { id: 'beijing_olympics', year: 2008, track: 'China', title: 'Beijing Olympic Games', title_zh: '北京奥运会', tags: ['sport', 'globalization'] },
  { id: 'arab_spring', year: 2010, track: 'World', title: 'Arab Spring', title_zh: '阿拉伯之春', tags: ['revolution', 'protest'] },
  { id: 'covid19', year: 2020, track: 'World', title: 'COVID-19 Pandemic', title_zh: '新冠疫情大流行', tags: ['health', 'global crisis'] },
];
